#!/usr/bin/env python
# -*- coding: utf-8 -*-

import Tkinter
import tkFileDialog
import tkMessageBox


top = Tkinter.Tk()
top.title(u'文件内容检索')
top.minsize(500, 200)
top.maxsize(800, 600)


lbl1 = Tkinter.StringVar()
label1 = Tkinter.Label(top, textvariable=lbl1, relief=Tkinter.FLAT).place(x=10, y=15)
lbl1.set(u"选择检索路径：")

lbl2 = Tkinter.StringVar()
label2 = Tkinter.Label(top, textvariable=lbl2, relief=Tkinter.FLAT, wraplength=250,
                       justify="left").place(x=100, y=15, width=250)


file_path = ''
def choose_path():
    global file_path
    file_path = tkFileDialog.askdirectory()
    lbl2.set(file_path)

def start_searching():
    if file_path == '':
        tkMessageBox.showinfo(u"提示", u"请选择检索的文件路径")

btn1 = Tkinter.Button(top, text=u"选择...", command=choose_path).place(x=360, y=10)
btn2 = Tkinter.Button(top, text=u"开始检索", command=start_searching).place(x=420, y=10)


top.mainloop()

